### ISSUE TITLE
An opportunity to store the result into stringIO/cStringIO

### ISSUE THREAD

**Issue by Zdenek24** [ConvertAPI/convertapi-python#1]
Would be possible to update method ResultFile.save() or create a new method which will be able to store downloaded content of the converted file into a stringIO/cStringIO object?

**Comment by laurynas-convertapi** [comment]
Hi @Zdenek24, I have created a PR adding file IO: https://github.com/ConvertAPI/convertapi-python/pull/3

It would return `io.BytesIO`.

**Comment by laurynas-convertapi** [comment]
Released `1.1.0` version. It allows getting result file IO: `result.file.io`.
