### ISSUE TITLE
Converting files from data, and not from path

### ISSUE THREAD

**Issue by gali-paz** [ConvertAPI/convertapi-python#13]
Hi, is there a way to send the data of a file, instead of the a path to the file? I'm asking because I'm generating files with code and then want to convert them to pdfs, without saving them on the computer. 
Thanks!

**Comment by laurynas-convertapi** [comment]
Hi @gali-paz, I have created simple data stream conversion example:
https://github.com/ConvertAPI/convertapi-python/blob/master/examples/convert_stream.py
