### ISSUE TITLE
"Unable to access the file." or "Unable to download the file" errors in Django

### ISSUE THREAD

**Issue by MatejMijoski** [ConvertAPI/convertapi-python#16]
I keep getting " Unable to access the file. Code: 5008." or "Unable to download the file" errors and I'm not sure why. I've browsed through the website but there's nothing there. 

I'm using the API in Django and here's my code:
```
convertapi.api_secret = 'my-secret'
result = convertapi.convert('pdfa', {'File': currFile[0].file.url})
```
in which currFile[0].file.url giver the URL of the file i.e. /file/tmp/name-of-file.png.

**Comment by laurynas-convertapi** [comment]
Hey @MatejMijoski,

please make sure local file exists. I have test using your example and it works fine for me

```python
result = convertapi.convert(
    'pdfa',
    {
        'File': './files/test.pdf'
    },
)

saved_files = result.save_files('/tmp')

print("The web page PDF saved to %s" % saved_files)
```

Also with remote file:
```python
result = convertapi.convert(
    'pdfa',
    {
        'File': 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
    },
)

saved_files = result.save_files('/tmp')

print("The web page PDF saved to %s" % saved_files)
```

**Comment by tomasr78** [comment]
@MatejMijoski Two days ago we had a temporary issue with the service for about 15 minutes, maybe it was the problem causing these two errors. Could you please try again?
