### ISSUE TITLE
Multiprocessing module not allowing children processes

### ISSUE THREAD

**Issue by iliyanotlioneberia** [ConvertAPI/convertapi-python#19]
I am seeing this error when running convertapi module inside celery task (even with -P threads). In utils.py the `multiprocessing` module is not happy when ran inside celery and it fails with:

    AssertionError: daemonic processes are not allowed to have children

Is there a workaround to this?

**Comment by laurynas-convertapi** [comment]
Hi @iliyanotlioneberia,

you can disable multiprocessing by setting `max_parallel_uploads` to 1:
`convertapi.max_parallel_uploads = 1`
