### ISSUE TITLE
I am facing 500:Internal Server Error for URL in version 1.4.0

### ISSUE THREAD

**Issue by priyamshah112** [ConvertAPI/convertapi-python#20]
![image](https://user-images.githubusercontent.com/25688111/114995120-1eef3c00-9ebb-11eb-82b8-2134983e634c.png)
Whenever, i am trying to make a call from localhost or from production server to 	

```
convertapi.convert('pdf', {
		'File': 'static/output/'+userId+'/excel.xlsx'
	}, from_format = 'xlsx').save_files('static/output/'+userId)
```

It's throwing the same error and the fun fact is the statistics page shows API was hit and deducts my time for failed attempts also which is totally wrong from a business perspective.
![image](https://user-images.githubusercontent.com/25688111/114995641-ac329080-9ebb-11eb-8662-75d54524fe31.png)

**Comment by tomasr78** [comment]
It could be a problem with the file. Please try to convert the file at https://www.convertapi.com/xlsx-to-pdf
What result do you get?

**Comment by priyamshah112** [comment]
From GUI to, it shows same error
![Screenshot 2021-04-17 102717](https://user-images.githubusercontent.com/25688111/115102714-39ccb980-9f6a-11eb-8f4d-273abb40fa52.png)

I did checked all the sheets, but no idea why its not able to convert xlsx file to pdf

**Comment by priyamshah112** [comment]
Thanks for the help, I re-generated the sheet and then tried making a call it worked. You were right it was problem with file.

**Comment by priyamshah112** [comment]
Maybe we can add some more details in the error message for such cases where the file is corrupted
