### ISSUE TITLE
Incorrect Links in the readme and documentation

### ISSUE THREAD

**Issue by abhishekmadhu** [ConvertAPI/convertapi-python#22]
I am trying to understand how to specify the page size of the output pdf when I am trying to convert a source excel to PDF. 
I came looking for the docs, and found a section called "Additional conversion parameters" in the [official documentation](https://www.convertapi.com/doc/python-library) as well as the [README](https://github.com/ConvertAPI/convertapi-python#file-conversion). 
The first paragraph of the section promises that "All conversion parameters and explanations can be found [here](https://www.convertapi.com/)." 

![image](https://user-images.githubusercontent.com/21152008/126499943-19a7d469-3304-4cc6-a8bb-7e189d545f83.png)

If we go to that page, **we expect to find a list of all conversion parameters and explanations**. Instead, **_we reach the home page of convertAPI where these details are not available_**. 

How to find that list? Once found, I will send a PR with the link modified.

**Comment by laurynas-convertapi** [comment]
Thanks for the report. Updated the link.
