### ISSUE TITLE
Do not pass any TimeOut property to ConvertAPI and set HTTP Client timeout to 1800 seconds

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-python#27]
Do not pass any default TimeOut property to ConvertAPI and set HTTP Client timeout to 1800 seconds. The idea is to use the default converter timeout of ConvertAPI if no timeout is set and to prevent HTTP Client request deadlock and set the default HTTPClient timeout to 1800 seconds.

If, however, timeout is set we handle it as before, pass a timeout to ConvertAPI and set HTTPClient Timeout to: ConvertAPITimeOut+conversion_timeout_delta

conversion_timeout_delta = 10

**Comment by tomasr78** [comment]
@laurynas-baltsoft Could you confirm that the TimeOut property is not hardcoded into the library and can be passed freely as all other properties?

**Comment by laurynas-convertapi** [comment]
There is no default conversion timeout. Changed default http timeout to 1800 and released `v1.5.0` version:
https://github.com/ConvertAPI/convertapi-python/releases/tag/v1.5.0
