### ISSUE TITLE
Deactivate SSL Certrificate verification?

### ISSUE THREAD

**Issue by tobtietze** [ConvertAPI/convertapi-python#33]
Hi, applying the following code I get a SSLCertVerificationError:

import convertapi
convertapi.api_secret = 'your-api-secret'
result = convertapi.convert('pdf', { 'File': '/path/to/my_file.docx' })
result.file.save('/path/to/save/file.pdf')

Is there a possibility to deactivate the verification? E.g. as when using the requests package directly with verify=False.

**Comment by laurynas-convertapi** [comment]
Added an option to disable SSL  verification:
https://github.com/ConvertAPI/convertapi-python/pull/34

Released in version 1.6.0.
