### ISSUE TITLE
Alternative converter parameter is case-sensitive

### ISSUE THREAD

**Issue by kostas-jonauskas** [ConvertAPI/convertapi-python#35]
The customer complains that the "converter" parameter is case-sensitive and doesn't work as we described in our auto-generated code snippet:

![image](https://user-images.githubusercontent.com/62603039/216938803-d73c8c28-2791-471a-a795-8080a7853855.png)

This Python code doesn't switch Converter type - it stays default.

```
convertapi.api_secret = 'your-api-secret'
convertapi.convert('pdf', {
'File': '/path/to/my_file.csv',
'Converter': 'Printer'
}, from_format = 'csv').save_files('/path/to/dir')
```

But if I change the "Converter" key "converter" key - it starts working. In GitHub the function uses param["converter"]
https://github.com/ConvertAPI/convertapi-python/blob/master/convertapi/task.py

**Comment by tomasr78** [comment]
@laurynas parameters name must be case-insensitive.
