### ISSUE TITLE
Set conversion location option

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-python#36]
Allow developers to set endpoint base URL, and add a description to readme how to do that. 

This is example how is done in C#

https://github.com/ConvertAPI/convertapi-dotnet#set-conversion-location-optional

**Comment by laurynas-convertapi** [comment]
It can already be set like this:
```
convertapi.api_base = 'https://my-custom-url/'
```
https://github.com/ConvertAPI/convertapi-python/blob/master/convertapi/__init__.py#L11
