### ISSUE TITLE
Convert PDF to DOCX: List with bulletpoints has different spaces

### ISSUE THREAD

**Issue by alfeilex** [ConvertAPI/convertapi-python#42]
Hello, 

thanks for your API and your great work. 

I have been trying to use the ConvertAPI to convert a PDF to DOCX. It works quite well but I have some problems with lists. There is different space between the bullet and the entry like in this image:

![grafik](https://github.com/ConvertAPI/convertapi-python/assets/101652401/edfc4270-0788-4b41-95ef-5d6c48f7a189)

Can I use some additional parameters or do you have any suggestions to solve this problem?

**Comment by tomasr78** [comment]
This question is not related to the python library.
