### ISSUE TITLE
Token authentication method

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-python#43]
Implement token authentication method.
https://www.convertapi.com/doc/auth#token

**Comment by tomasr78** [comment]
This is how it is implemented in the C# library  

https://github.com/ConvertAPI/convertapi-dotnet/blob/1a70b692e2416be2f284880a6f3eef9abb868bc4/ConvertApi/ConvertApi.cs#L46

**Comment by laurynas-convertapi** [comment]
Implemented in https://github.com/ConvertAPI/convertapi-python/releases/tag/v1.8.0
