### ISSUE TITLE
Use Bearer authentication

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-python#48]
Change query authentication to bearer authentication.

`curl -X GET https://v2.convertapi.com/user -H 'Authorization: Bearer secret_or_token'`

**Comment by tomasr78** [comment]
The property that accepts the secret is `convertapi.api_secret = 'xxxxxx'`. I suggest renaming it to `api_credentials`  because it will match the idea that a secret or token is accepted and not only a secret.

**Comment by laurynas-convertapi** [comment]
Released in version https://github.com/ConvertAPI/convertapi-library-python/releases/tag/v2.0.0
