### ISSUE TITLE
Problems with Docx Compare API

### ISSUE THREAD

**Issue by KevWilcz** [ConvertAPI/convertapi-python#54]
Hello,

since two days know the compare API is not working for us and we can not figure out why. Can you look at the screenshot and see if you find the reason?

We really look forward to your help.

Best regards,Kevin![image](https://github.com/user-attachments/assets/b88703bc-d693-4e46-b6be-687c63e6dc10)

**Comment by KevWilcz** [comment]
It was beause of the python version. We used the newest one, which is not supported

**Comment by laurynas-convertapi** [comment]
I assume the issue was with API credentials not being set, not with python version.

You can set API credentials like this:

```python
import convertapi

convertapi.api_credentials = 'your-api-secret-or-token'
```
