### ISSUE TITLE
Error while installing convertapi in python 3.8 for windows 

### ISSUE THREAD

**Issue by s-asish** [ConvertAPI/convertapi-python#9]
pip install --upgrade convertapi  
I got below error. Please help me

ERROR: Could not find a version that satisfies the requirement convertapi (from versions: none)
ERROR: No matching distribution found for convertapi

Regards
Asish

**Comment by laurynas-convertapi** [comment]
Hi @s-asish, I suggest to try using `pip3`:
```
pip3 install --upgrade convertapi
```
